### PR TITLE
Made the plugin work again after changes by NPO on 28-02-2017

### PR DESCRIPTION
**Pull request by mrarends**
Changed the API URL and the media URL's.

### CODE REVIEW

**Comment by misa2610** [comment]
Thanks and working again

**Comment by xoref** [comment]
Thanks for the update. I've updated the nederland24.py file on my Kodi (LibreElec) and only NOS Achtuurjournaal seems to work, the log gives me the following output:

```
19:18:36.434 T:139743241132160   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://pedgewarea22b.video.kpnstreaming.nl:80/session/7c873386-feab-11e6-b339-1458d04270a0/fqimjj/b2b/live/npo/live/npo/tvlive/npo2/npo2.isml/npo2.m3u8
19:18:36.489 T:139743241132160  NOTICE: VideoPlayer: Opening: http://pedgewarea22b.video.kpnstreaming.nl:80/session/7c873386-feab-11e6-b339-1458d04270a0/fqimjj/b2b/live/npo/live/npo/tvlive/npo2/npo2.isml/npo2.m3u8
19:18:36.489 T:139743241132160 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
19:18:36.501 T:139743241132160   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://pedgewarea22b.video.kpnstreaming.nl:80/session/7c873386-feab-11e6-b339-1458d04270a0/fqimjj/b2b/live/npo/live/npo/tvlive/npo2/npo2.isml/npo2.m3u8
19:18:36.502 T:139741726930688  NOTICE: Creating InputStream
19:18:36.610 T:139741726930688   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
19:18:36.611 T:139741726930688   ERROR: CCurlFile::Open failed with code 403 for http://pedgewarea22b.video.kpnstreaming.nl:80/session/7c873386-feab-11e6-b339-1458d04270a0/fqimjj/b2b/live/npo/live/npo/tvlive/npo2/npo2.isml/npo2.m3u8
19:18:36.611 T:139741726930688  NOTICE: Creating Demuxer
19:18:36.620 T:139741726930688   ERROR: OpenDemuxStream - Error creating demuxer
19:18:36.620 T:139741726930688  NOTICE: CVideoPlayer::OnExit()
19:18:36.620 T:139743241132160   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nederland24/?url=LI_NL2_4188105&mode=playVideo]
```

If I try to mimic the request with my browser I get a `{"error":"Access denied"}`

**Comment by sphaero** [comment]
Just tried the changes and can confirm it works for NPO1, NPO2 & NPO3 (using telfort provider)

**Comment by mrarends** [comment]
I have found something in the HAR file. The regex's incorrectly presumes the urls are ending on url and m3u8. With KPN streaming there is a token added to the URLs which we are missing now.

Lets see if I can change the regex's to always include the whole urls.

**Comment by mrarends** [comment]
@xoref Can you please test the new version?

**Comment by SLKTH** [comment]
I have Tele2 and  can confirm that it's working. Haven't tested the other channels yet, but I'm quite sure they will work too. 

Watching NPO 1 currently. :)
 
Thanks @mrarends!

**Comment by sciurius** [comment]
Bij mij werkt het weer!

**Comment by nsteur** [comment]
Beste mrarends, moet ik iets doen om de nederland24 addon weer te laten werken? Of moet ik wachten tot een nieuwe update?

**Comment by xoref** [comment]
@nsteur Update het nederland24.py bestand in de addon map van de plugin van je Kodi installatie:
1. Save de volgende URL als `nederland24.py`: https://raw.githubusercontent.com/mrarends/plugin.video.nederland24/204f19bc7bf0f00a3088e25ea9d694ea9b1a681c/nederland24.py
2. Kopieer `nederland24.py` naar de addon map van je Kodi installatie en vervang het al bestaande `nederland24.py` bestand (bij LibreElec is dat in `/storage/.kodi/addons/plugin.video.nederland24/` )

@mrarends Thanks for the update, will test it asap!

**Comment by marcknijn** [comment]
@mrarends thanks!

**Comment by matthijsvh** [comment]
Thank you. Here is a installable ZIP.
[plugin.video.nederland24.zip](https://github.com/bosel/plugin.video.nederland24/files/815298/plugin.video.nederland24.zip)

**Comment by nsteur** [comment]
Thanks allemaal, werkt weer als een zonnetje!

**Comment by bosel** [comment]
@mrarends Cheers!

**Pull request merged**
